name: Generate API docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: yarn install

    - name: Generate API docs
      run: yarn docusaurus gen-api-docs all

    - name: Commit changes
      run: |
        git add docs/api
        git commit -m "Generate API docs"
        git push
